name: Deploy to Arweave

on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Misc. Deps
        run: sudo apt-get install -y libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

      - name: Install corepack
        run: npm i -g corepack

      - name: Install pnpm
        run: npm i -g --force corepack && corepack enable pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Comparison of locales for missing keys
        run: pnpm compare-locales

      - name: Publish to Arweave
        # deploy:arweave calls buildandexport
        run: pnpm deploy:arweave
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ARNS_NAME: ${{ secrets.ARNS_NAME }}
